-- Intentionally disabled.
-- The Mini Pack tree door uses TARDIS's existing core part with ID "door".
-- Its standard implementation drives the model's "switch" pose parameter and
-- synchronizes the interior/exterior door state. Do not register a competing
-- lighthouse-specific part here.
